name: Kse Docs Build
description: Generate docs for kse
title: "[Docs] <kse>"
body:
  - type: dropdown
    id: Kse
    attributes:
      label: Version of kse
      description: What version of kse are you need?
      multiple: false
      options:
        - kse-v3.3
        - kse-v3.4
        - kse-v3.5
        - kse-v4.0
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Kubernetes
    attributes:
      label: Version of kubernetes
      description: What version of kubernetes are you need?
      multiple: false
      options:
        - kubernetes-v1.21
        - kubernetes-v1.22
        - kubernetes-v1.23
        - kubernetes-v1.24
        - kubernetes-v1.25
        - kubernetes-v1.26
        - kubernetes-v1.27
        - kubernetes-v1.28
      default: 0
    validations:
      required: true