pipeline {
  agent {
    baseubuntu {
      label 'baseubuntu'
    }
  }

  stages {
    stage('baseubuntu hello') {
      steps {
        container('baseubuntu') {
          sh 'cd base-image && make build-alpine-edge'
        }
      }
     }
   }
}
