FROM ubuntu:20.04

ARG TARGETARCH

RUN apt-get -y update && \
    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release && \
    curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    set -eux && \
    if [ ${TARGETARCH} = "amd64" ];then \
    echo "deb [arch=amd64  signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.aliyun.com/docker-ce/linux/ubuntu \
              $(lsb_release -cs) stable"|tee /etc/apt/sources.list.d/docker.list >/dev/null; \
    elif [ ${TARGETARCH} = "arm64" ];then \
    echo "deb [arch=arm64  signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.aliyun.com/docker-ce/linux/ubuntu \
              $(lsb_release -cs) stable"|tee /etc/apt/sources.list.d/docker.list >/dev/null; \
    fi && \
    apt-get -y update && \
    apt-get install -y docker-ce-cli

RUN apt-get install -y make libpam0g-dev



