name: grype-image-scan

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io

jobs:
  ks-apiserver-scan:

    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
#      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
#      id-token: write
      security-events: write

    steps:
      - name: Run the Anchore Grype scan action
        uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
        id: scan
        with:
          image: "docker.io/2030047311/ks-apiserver:v3.3.2-20230428"
          fail-build: false
          severity-cutoff: critical
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      
  ks-controller-manager-scan:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Run the Anchore Grype scan action
        uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
        id: scan
        with:
          image: "docker.io/2030047311/ks-controller-manager:v3.3.2-20230428"
          fail-build: false
          severity-cutoff: critical

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}