name: security-image-scan

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: registry.cn-beijing.aliyuncs.com/kse/

jobs:
  grype-ks-apiserver-image-scan:

    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      security-events: write


    steps:
      - name: Run the Anchore Grype scan action
        uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
        id: scan
        with:
          image: ${{ env.REGISTRY }}ks-apiserver:v3.4.0
          fail-build: false
          severity-cutoff: critical

      - name: Upload Grype scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}


  grype-ks-controller-manager-scan:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Run the Anchore Grype scan action
        uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
        id: scan
        with:
          image: ${{ env.REGISTRY }}ks-apiserver:v3.4.0
          fail-build: false
          severity-cutoff: critical

      - name: Upload Grype scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}


  trivy-ks-apiserver-image-scan:

    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      security-events: write


    steps:
      - name: Run the Anchore Grype scan action
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ env.REGISTRY }}ks-apiserver:v3.4.0
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'


  trivy-ks-controller-manager-scan:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Run the Anchore Grype scan action
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ env.REGISTRY }}ks-apiserver:v3.4.0
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'