name: security-image

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: docker.io

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v5
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image -- alpine
        id: build-and-push-alpine
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./security-image/nodejs/
          file: Dockerfile
          platforms: linux/arm64, linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: 2030047311/nodejs20:edge
          cache-from: type=gha
          cache-to: type=gha,mode=max
#      -
#        run: cd ./security-image/ && make build-nodejs20-multi-platform