name: SecurityImageScan

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    inputs: []

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: registry.cn-beijing.aliyuncs.com/kse/
  TAG: v3.4.0
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:

  TrivyImageScan:

    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      security-events: write


    steps:
      - name: Run the Trivy scan action
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ env.REGISTRY }}ks-apiserver:${{ env.TAG }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Add some comments.
            
            你好 @${{ github.event.issue.user.login }}。巴拉巴拉。
            emoji: '+1' or '+1,heart'